spring:
  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

  application:
    name: RetailerAndProductManagement

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/testDb
    username: postgres
    password: murad2016
    driver-class-name: org.postgresql.Driver

server:
  port: 8998
